version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    env_file:
      - ../.env   # important fix (since docker folder)
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: